# Generated by Django 4.1.7 on 2023-10-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="body", field=models.TextField(),
        ),
    ]
