# Generated by Django 4.1.7 on 2023-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="last_edit_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
