# Generated by Django 4.1.7 on 2023-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="publication_date", field=models.DateTimeField(),
        ),
    ]
