# Generated by Django 4.1.7 on 2023-10-16 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_comment_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="text", field=ckeditor.fields.RichTextField(),
        ),
    ]
