# Generated by Django 4.1.7 on 2023-10-16 19:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="body", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="comment", name="text", field=models.TextField(),
        ),
    ]
