# Generated by Django 4.1.7 on 2023-10-16 19:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_article_body_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
