# Generated by Django 4.1.7 on 2023-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_in_polish",
            field=models.BooleanField(default=False),
        ),
    ]
