# Generated by Django 4.1.7 on 2023-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_article_is_in_polish"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
