# Generated by Django 4.1.7 on 2023-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_article_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
