# Generated by Django 4.1.7 on 2023-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
